### ISSUE TITLE
Unable to log into app

### ISSUE THREAD

**Issue by nightkingdoms** [chadsmith/OpenVBX-Android#3]
Always unable to login.  Tried 2 different accounts.  Tried changing passwords (even 12341234) and could never login.  Server normally runs SSL and even dropped to http:// and still no change.  App recognizes the OpenVBX installation address but never logs in.

Login Failed
Your email address or password is invalid.

**Comment by chadsmith** [comment]
This should be resolved in the latest version. Let me know if that's not the case.

**Comment by AmalgamationWunderkindStudios** [comment]
Interesting nobody came back here to report the bug still existing 

Tried it on a few different versions of android and still get that same login failure or then occasionally I'll go to open the app from screen icon after its been sitting idle for hours and then get a blank interface except with a dial pad on it.

Amazing work so far and if you can get this working I'd drop you a personal donation for your time ;)
